### PR TITLE
ConstraintFilterTest.php: addRequiredField()

### PR DESCRIPTION
**Pull request by boekhorstb1**
**Question concerning **addRequiredField($field)** as tested in **testFilterAcceptsWhenRequiredFieldisPresent****

1. I did not found a way to add a custom field called, e.g. "my_custom_field" as has been done in ConstraintTest.php. So one cannot mark a custom field as "required"
2. I think the existing fields "message" and "level" are required already. Fields like "context" seems to be set to a default value, when I try to "addRequiredField($field = "context")" I get errors. 
**NB:** I have not manage to test with the field "formattedMessage" yet.

### CODE REVIEW

**Comment by boekhorstb1** [comment]
**I converted all tests from ConstraintTest.php to ConstraintFilterTest.php**

But: not sure it is possible to set other fields (other than "message", "level", "context", "formatMessage")
Also: It appears that only the "message" field is searchable by regex. It also seems that only the "message" field can be constrained.

**Comment by midahp** [comment]
You can set custom fields in the context parameter of LogMessage and then add them as required:
```
new LogMessage($this->level2, $this->message2, ['customField' => 'customValue']);
$filterator->addRequiredField('customField')
```
Also the level is in the field `loglevel` und the field `timestamp` is automatically generated.

**Comment by midahp** [comment]
Can you also add a test for `addRequiredFields`?

**Comment by boekhorstb1** [comment]
Thanks! I will add the test

**Comment by boekhorstb1** [comment]
customfield has been added

**Comment by midahp** [comment]
It's a small thing but can you add a test for `addRequiredFields` as mentioned?

**Comment by boekhorstb1** [comment]
> You can set custom fields in the context parameter of LogMessage and then add them as required:
> 
> ```
> new LogMessage($this->level2, $this->message2, ['customField' => 'customValue']);
> $filterator->addRequiredField('customField')
> ```
> 
> Also the level is in the field `loglevel` und the field `timestamp` is automatically generated.

Ok I will add a test `addRequiredFields` as mentioned in reply

**Comment by boekhorstb1** [comment]
Im not sure I fully got it, but please see **testFilterAcceptsWhenRequiredFieldisPresent()** which tests if the custom field is set correctly. I added the context directly as an array now.

**Comment by midahp** [comment]
> Im not sure I fully got it, but please see **testFilterAcceptsWhenRequiredFieldisPresent()** which tests if the custom field is set correctly. I added the context directly as an array now.

Your tests for `addRequiredField` are great, I just wanted you to add a test for `addRequiredFields` to cover all methods.

**Comment by boekhorstb1** [comment]
aa alright! I overlooked that method, I missed the 's', will add a testmethod

**Comment by boekhorstb1** [comment]
added to test method for checking when multiple fields are required and present/absent

**Review by midahp — APPROVED** [review]

**Pull request merged**
